# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebfe8b631a590d2cedf85fb1a6cb0f9ca80dd3fa98fab84d763400822f1599f9f95c029c6558f3644d3223351489d03d2c685ff344fb1ea02c072a38bba99047

test:
  secret_key_base: fa7591fab94addd501dd33747de246c22ad585f56d57a84e7b2b696a100b0fce289f6fbd5283a0523232f40d871ae597f69a4a1498440d3af1c5cf4c68081a34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
